sudo: required

language: java

jdk:
  - oraclejdk8
  - openjdk8

services:
  - docker

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - sudo /etc/init.d/postgresql stop

install:
  - export WORKSPACE="$(pwd)/workspace"
  - mkdir $WORKSPACE
  - git clone https://github.com/apiman/apiman $WORKSPACE/apiman > /dev/null
  - git clone https://github.com/apiman/apiman-plugins $WORKSPACE/apiman-plugins > /dev/null
  - echo "export TEST_SOURCES=$(pwd)" | tee --append tools/scripts/travis/installrc.sh tools/scripts/travis/scriptrc.sh
  - export RC_FILE=tools/scripts/travis/installrc.sh
  - travis_wait 30 bash -x tools/scripts/travis/travis_run.sh

before_script:
  - sed -i.bak -e 's|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|https://nexus.codehaus.org/snapshots/|g' ~/.m2/settings.xml

script: 
  - export WORKSPACE="$(pwd)/workspace"
  - RC_FILE=tools/scripts/travis/scriptrc.sh bash -x tools/scripts/tests_runner.sh

notifications:
  email:
    - miroslav.jaros91@gmail.com

branches:
  only:
    - travis
